<?xml version="1.0" encoding="utf-8"?><Database Name="DB_A2615F_JNV" Class="JNVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql5009.smarterasp.net;Initial Catalog=DB_A2615F_JNV;User ID=DB_A2615F_JNV_admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_A2615F_JNVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_about_us" Member="tbl_about_us">
    <Type Name="tbl_about_us">
      <Column Name="About_Us_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="About_Us" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_videos" Member="tbl_videos">
    <Type Name="tbl_video">
      <Column Name="Video_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Video_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Album_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_advertisements" Member="tbl_advertisements">
    <Type Name="tbl_advertisement">
      <Column Name="Advertisement_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Advertisement_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_city_master" Member="tbl_city_masters">
    <Type Name="tbl_city_master">
      <Column Name="City_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="State_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_contact_us" Member="tbl_contact_us">
    <Type Name="tbl_contact_us">
      <Column Name="Contact_Us_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Contact_Us" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_events" Member="tbl_events">
    <Type Name="tbl_event">
      <Column Name="Event_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Event_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Event_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_pictures" Member="tbl_pictures">
    <Type Name="tbl_picture">
      <Column Name="Picture_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Picture_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Album_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_posts" Member="tbl_posts">
    <Type Name="tbl_post">
      <Column Name="Post_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Post_Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Post_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_state_master" Member="tbl_state_masters">
    <Type Name="tbl_state_master">
      <Column Name="State_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="State_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_teachers" Member="tbl_teachers">
    <Type Name="tbl_teacher">
      <Column Name="Teacher_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Teacher_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="School" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_users" Member="tbl_users">
    <Type Name="tbl_user">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nick_name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WhatsApp_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Admission_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MemberType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Father_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Village" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Sport_And_Level" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Hobbies" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="JNV_School" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passout_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_From" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_To" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Place_From_Selected" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Academic_Detail" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Profession_Detail" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Home_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Current_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Facebook_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LinkedIn_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Twitter_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tbl_Role_tbl_user" Member="tbl_Role" ThisKey="Role" OtherKey="RoleID" Type="tbl_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Roles" Member="tbl_Roles">
    <Type Name="tbl_Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="tbl_Role_tbl_user" Member="tbl_users" ThisKey="RoleID" OtherKey="Role" Type="tbl_user" />
    </Type>
  </Table>
  <Function Name="dbo.CheckUserValidate" Method="CheckUserValidate">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="CheckUserValidateResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nick_name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WhatsApp_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Admission_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MemberType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Father_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Village" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Sport_And_Level" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Hobbies" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="JNV_School" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passout_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_From" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_To" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Place_From_Selected" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Academic_Detail" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Profession_Detail" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Home_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Current_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Facebook_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LinkedIn_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Twitter_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Upd_user_By_ID" Method="Upd_user_By_ID">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Nick_Name" Parameter="nick_Name" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Role" Parameter="role" Type="System.Int32" DbType="Int" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="WhatsApp_Number" Parameter="whatsApp_Number" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="State_ID" Parameter="state_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Admission_year" Parameter="admission_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MemberType" Parameter="memberType" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Father_Name" Parameter="father_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Marital_Status" Parameter="marital_Status" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Village" Parameter="village" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Sport_And_Level" Parameter="sport_And_Level" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Hobbies" Parameter="hobbies" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="JNV_School" Parameter="jNV_School" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Passout_Year" Parameter="passout_Year" Type="System.Int32" DbType="Int" />
    <Parameter Name="Batch_From" Parameter="batch_From" Type="System.Int32" DbType="Int" />
    <Parameter Name="Batch_To" Parameter="batch_To" Type="System.Int32" DbType="Int" />
    <Parameter Name="Place_From_Selected" Parameter="place_From_Selected" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Academic_Detail" Parameter="academic_Detail" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Profession_detail" Parameter="profession_detail" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="home_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Current_Address" Parameter="current_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Facebook_ID" Parameter="facebook_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LinkedIn_ID" Parameter="linkedIn_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Twitter_ID" Parameter="twitter_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Photo" Parameter="photo" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Del_Admin_By_ID" Method="Del_Admin_By_ID">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Events_By_CityID" Method="Get_Events_By_CityID">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Events_By_CityIDResult">
      <Column Name="Event_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Event_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Event_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_Pictures_By_CityID" Method="Get_Pictures_By_CityID">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Pictures_By_CityIDResult">
      <Column Name="Picture_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Picture_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Album_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_Post_By_CityID" Method="Get_Post_By_CityID" IsComposable="true">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.Get_Profile_By_UserID" Method="Get_Profile_By_UserID">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Profile_By_UserIDResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nick_name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WhatsApp_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Admission_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MemberType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Father_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Village" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Sport_And_Level" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Hobbies" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="JNV_School" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passout_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_From" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_To" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Place_From_Selected" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Academic_Detail" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Profession_Detail" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Home_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Current_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Facebook_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LinkedIn_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Twitter_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_Users_For_Notification" Method="Get_Users_For_Notification">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Users_For_NotificationResult">
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_Videos_By_CityID" Method="Get_Videos_By_CityID">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Videos_By_CityIDResult">
      <Column Name="Video_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Video_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Album_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Set_AboutUs" Method="Set_AboutUs">
    <Parameter Name="About_Us" Parameter="about_Us" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Set_Picture" Method="Set_Picture">
    <Parameter Name="Picture_Name" Parameter="picture_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Album_Name" Parameter="album_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Set_Post" Method="Set_Post">
    <Parameter Name="Post_Description" Parameter="post_Description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Post_Date" Parameter="post_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Set_Video" Method="Set_Video">
    <Parameter Name="Video_Name" Parameter="video_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Album_Name" Parameter="album_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Upd_Admin_By_ID" Method="Upd_Admin_By_ID">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Nick_Name" Parameter="nick_Name" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Role" Parameter="role" Type="System.Int32" DbType="Int" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="WhatsApp_Number" Parameter="whatsApp_Number" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="State_ID" Parameter="state_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Admission_year" Parameter="admission_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MemberType" Parameter="memberType" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Father_Name" Parameter="father_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Marital_Status" Parameter="marital_Status" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Village" Parameter="village" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Sport_And_Level" Parameter="sport_And_Level" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Hobbies" Parameter="hobbies" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="JNV_School" Parameter="jNV_School" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Passout_Year" Parameter="passout_Year" Type="System.Int32" DbType="Int" />
    <Parameter Name="Batch_From" Parameter="batch_From" Type="System.Int32" DbType="Int" />
    <Parameter Name="Batch_To" Parameter="batch_To" Type="System.Int32" DbType="Int" />
    <Parameter Name="Place_From_Selected" Parameter="place_From_Selected" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Academic_Detail" Parameter="academic_Detail" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Profession_detail" Parameter="profession_detail" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="home_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Current_Address" Parameter="current_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Facebook_ID" Parameter="facebook_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LinkedIn_ID" Parameter="linkedIn_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Twitter_ID" Parameter="twitter_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Photo" Parameter="photo" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Set_Registration" Method="Set_Registration">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Nick_Name" Parameter="nick_Name" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Role" Parameter="role" Type="System.Int32" DbType="Int" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="WhatsApp_Number" Parameter="whatsApp_Number" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="State_ID" Parameter="state_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Admission_year" Parameter="admission_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MemberType" Parameter="memberType" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Father_Name" Parameter="father_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Marital_Status" Parameter="marital_Status" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Village" Parameter="village" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Sport_And_Level" Parameter="sport_And_Level" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Hobbies" Parameter="hobbies" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="JNV_School" Parameter="jNV_School" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Passout_Year" Parameter="passout_Year" Type="System.Int32" DbType="Int" />
    <Parameter Name="Batch_From" Parameter="batch_From" Type="System.Int32" DbType="Int" />
    <Parameter Name="Batch_To" Parameter="batch_To" Type="System.Int32" DbType="Int" />
    <Parameter Name="Place_From_Selected" Parameter="place_From_Selected" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Academic_Detail" Parameter="academic_Detail" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Profession_detail" Parameter="profession_detail" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="home_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Current_Address" Parameter="current_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Facebook_ID" Parameter="facebook_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LinkedIn_ID" Parameter="linkedIn_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Twitter_ID" Parameter="twitter_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Photo" Parameter="photo" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Admin" Method="Get_Admin">
    <ElementType Name="Get_AdminResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nick_name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WhatsApp_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Admission_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MemberType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Father_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Village" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Sport_And_Level" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Hobbies" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="JNV_School" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passout_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_From" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_To" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Place_From_Selected" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Academic_Detail" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Profession_Detail" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Home_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Current_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Facebook_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LinkedIn_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Twitter_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_Admin_By_ID" Method="Get_Admin_By_ID">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Admin_By_IDResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nick_name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WhatsApp_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Admission_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MemberType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Father_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Village" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Sport_And_Level" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Hobbies" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="JNV_School" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passout_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_From" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Batch_To" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Place_From_Selected" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Academic_Detail" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Profession_Detail" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Home_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Current_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Facebook_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LinkedIn_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Twitter_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Upd_AboutUs_By_CityID" Method="Upd_AboutUs_By_CityID">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="About_Us" Parameter="about_Us" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_AboutUS_By_CityID" Method="Get_AboutUS_By_CityID">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_AboutUS_By_CityIDResult">
      <Column Name="About_Us_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="About_Us" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Set_ContatcUs" Method="Set_ContatcUs">
    <Parameter Name="Contact_Us" Parameter="contact_Us" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Upd_Contact_By_CityID" Method="Upd_Contact_By_CityID">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Contact_Us" Parameter="contact_Us" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_ContactUS_By_CityID" Method="Get_ContactUS_By_CityID">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_ContactUS_By_CityIDResult">
      <Column Name="Contact_Us_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Us" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_event_By_eventID" Method="Get_event_By_eventID">
    <Parameter Name="event_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_event_By_eventIDResult">
      <Column Name="Event_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Event_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Event_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Del_event_By_eventID" Method="Del_event_By_eventID">
    <Parameter Name="Event_ID" Parameter="event_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Set_Event" Method="Set_Event">
    <Parameter Name="Event_Name" Parameter="event_Name" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Event_Date" Parameter="event_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Upd_Event_By_EventID" Method="Upd_Event_By_EventID">
    <Parameter Name="Event_ID" Parameter="event_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Event_Name" Parameter="event_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Event_Date" Parameter="event_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Advertisement_By_AdvertisementID" Method="Get_Advertisement_By_AdvertisementID">
    <Parameter Name="Advertisement_ID" Parameter="advertisement_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Advertisement_By_AdvertisementIDResult">
      <Column Name="Advertisement_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Advertisement_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Del_Advertisement_By_AdvertisementID" Method="Del_Advertisement_By_AdvertisementID">
    <Parameter Name="Advertisement_ID" Parameter="advertisement_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Set_Advertisement" Method="Set_Advertisement">
    <Parameter Name="advertisement_Name" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="position" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Upd_Advertisement_By_AdvertisementID" Method="Upd_Advertisement_By_AdvertisementID" IsComposable="true">
    <Parameter Name="Advertisement_ID" Parameter="advertisement_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Advertisement_Name" Parameter="advertisement_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Position" Parameter="position" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.Get_Birthday_By_CityID" Method="Get_Birthday_By_CityID">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Birthday_By_CityIDResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_Birthday_By_CurrentDate" Method="Get_Birthday_By_CurrentDate">
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <ElementType Name="Get_Birthday_By_CurrentDateResult">
      <Column Name="Birthday" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Del_Teacher_By_TeacherID" Method="Del_Teacher_By_TeacherID">
    <Parameter Name="Teacher_ID" Parameter="teacher_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Teacher_By_TeacherID" Method="Get_Teacher_By_TeacherID">
    <Parameter Name="Teacher_ID" Parameter="teacher_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Teacher_By_TeacherIDResult">
      <Column Name="Teacher_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Teacher_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="School" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_Teachers_By_CityID" Method="Get_Teachers_By_CityID">
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Get_Teachers_By_CityIDResult">
      <Column Name="Teacher_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Teacher_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="School" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Set_Teacher" Method="Set_Teacher">
    <Parameter Name="Teacher_Name" Parameter="teacher_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="School" Parameter="school" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Subject" Parameter="subject" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="State_ID" Parameter="state_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Upd_Teacher_By_TeacherID" Method="Upd_Teacher_By_TeacherID">
    <Parameter Name="Teacher_ID" Parameter="teacher_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Teacher_Name" Parameter="teacher_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="School" Parameter="school" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Subject" Parameter="subject" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="City_ID" Parameter="city_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="State_ID" Parameter="state_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>